name: Create Release Package

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            svelte/*
            client.lua
            server.lua
            fxmanifest.lua
            config.lua
          token: ${{ secrets.GITHUB_TOKEN }}
